config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :blogs do
    post :new_confirm, on: :collection
    patch :edit_confirm, on: :member
  end
  resources :favorites, only: [:index, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    validates :title,
        presence: true,
        length: {in: 1..30, allow_blank: true}
    validates :content,
        presence: true,
        length: {in: 1..140, allow_blank: true}

    mount_uploader :image, ImageUploader
    # validates :image, check_image: true
    #
    # def check_image
    #   if !['.jpg', 'png', '.gif'].include?(File.extname(name).downcase)
    #     errors.add(:image, 'JPG, PNG, GIF以外の画像はアップロードできません')
    #   elsif file.size > 1.megabyte
    #     errors.add(:image, '1MBより大きい画像はアップロードできません')
    #   end
    # end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog, dependent: :destroy
  validates :name,
      presence: true,
      length: { maximum: 30, allow_blank: true }

  VALID_EMAIL_ADDRESS = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
      presence: true,
      length: { maximum: 255, allow_blank: true },
      format: { with: VALID_EMAIL_ADDRESS, allow_blank: true },
      uniqueness: true
  before_save { email.downcase! }

  has_secure_password
  validates :password,
      presence: true,
      length: { minimum: 6, allow_blank: true },
      allow_nil: true

  mount_uploader :image, ImageUploader
  # validates :image, check_image: true
  #
  # def check_image
  #   if !['.jpg', 'png', '.gif'].include?(File.extname(name).downcase)
  #     errors.add(:image, 'JPG, PNG, GIF以外の画像はアップロードできません')
  #   elsif file.size > 1.megabyte
  #     errors.add(:image, '1MBより大きい画像はアップロードできません')
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def forbidden_login_user
    if current_user
      flash[:danger] = "すでにログインしています。"
      redirect_to blogs_path
    end
  end

  def before_logged_in
    unless current_user
      flash[:danger] = "ログインしてください."
      redirect_to new_session_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only:[:show, :ensure_correct_post, :edit, :update, :destroy, :edit_confirm]
  before_action :before_logged_in
  before_action :ensure_correct_post, only:[:edit, :update]

  PER = 10

  def index
    @blogs = Blog.page(params[:page]).per(PER).reverse_order
  end

  def new
    if params[:back]
      @blog = current_user.blogs.new(blog_params)
    else
      @blog = current_user.blogs.new
    end
  end

  def create
    @blog = current_user.blogs.new(blog_params)
    @blog.image.retrieve_from_cache!(params[:cache][:image]) if params[:cache][:image].present?
    if @blog.save
      # NoticeMailer.notice_mail(@blog).deliver
      flash[:notice] = "新しい記事\"#{@blog.title}\"を投稿しました。"
      redirect_to blogs_path
    else
      render "new"
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
    if params[:back]
      @blog.attributes = blog_params
    end
  end

  def update
    @blog.attributes = blog_params
    @blog.image.retrieve_from_cache!(params[:cache][:image]) if params[:cache][:image].present?
    if @blog.save
      flash[:notice] = "記事\"#{@blog.title}\"を編集しました。"
      redirect_to blogs_path
    else
      render "edit"
    end
  end

  def destroy
    @blog.destroy
    flash[:notice] = "記事\"#{@blog.title}\"を削除しました。"
    redirect_to blogs_path
  end

  def new_confirm
    @blog = current_user.blogs.new(blog_params)
    render "new" unless @blog.valid?
  end

  def edit_confirm
    @blog.attributes = blog_params
    render "edit" unless @blog.valid?
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  # def edit_blog
  #   @blog = current_user.blogs.find(params[:id])
  # end

  def ensure_correct_post
    if current_user.id != @blog.user_id.to_i
      flash[:danger] = "権限がありません。"
      redirect_to blog_path(@blog.id)
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blog_path(params[:blog_id])
  end

  def destroy
    current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blog_path(params[:blog_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :forbidden_login_user, only:[:new, :create]

  def new
    render layout: 'top_page'
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "ログインしました。"
      redirect_to blogs_path
    else
      flash[:danger] = "ログインに失敗しました。"
      redirect_to new_session_path
    end
  end

  def destroy
     session.delete(:user_id)
     flash[:notice] = "ログアウトしました。"
     redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :forbidden_login_user
  def index
    render layout: 'top_page'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update, :ensure_correct_user, :blogs, :favorites]
  before_action :forbidden_login_user, only:[:new, :create]
  before_action :ensure_correct_user, only:[:edit, :update]

  def new
    @user = User.new
    render layout: 'top_page'
  end

  def create
    @user = User.new(users_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録に成功しました。"
      redirect_to blogs_path
    else
      render 'new'
    end
  end

    PER = 5

  def show
    @user_blogs = @user.blogs.page(params[:page]).per(PER).reverse_order
    @favorite_blogs = @user.favorite_blogs.page(params[:page]).per(PER).reverse_order
  end

  def blogs
  end

  def favorites
  end

  def edit
  end

  def update
    if @user.update(users_params)
      flash[:notice] = "ユーザー情報を更新しました。"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  private
    def users_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def ensure_correct_user
      if current_user.id != @user.id.to_i
        flash[:danger] = "権限がありません。"
        redirect_to user_path(@user.id)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def url_new_or_edit
    if action_name == "new" || action_name == "new_confirm"
      new_confirm_blogs_path
    elsif action_name = "edit" || action_name == "edit_confirm"
      edit_confirm_blog_path(@blog.id)
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_confirm.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>

  <section class="form row">
    <div class="title"><%= form.label :title %></div>
    <div class="content"><%= @blog.title %></div>

    <div class="title"><%= form.label :content %></div>
    <div class="content"><%= simple_format(@blog.content) %></div>
    <div class="blog-image"><%= image_tag(@blog.image.url) if @blog.image.present? %></div>
    <%= hidden_field_tag :"cache[image]", @blog.image.cache_name%>
  </section>

  <div class="confirm-submit-btn">
    <ul class="edit-menu col-md-2 col-sm-12">
      <li><%= form.submit "Submit.", id: 'btn' %></li>
    </ul>
  </div>
<% end %>

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: url_new_or_edit) do |form| %> <!--url/methodはhelper参照-->
  <% if @blog.errors.any? %>
    <div class="errors">
      <p><%= @blog.errors.count %>件のエラーがあります。</p>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <section class="form row">
    <div class="title"><%= form.label :title %></div>
    <div class="content"><%= form.text_field :title, class: 'text-title' %></div>

    <div class="title"><%= form.label :content %></div>
    <div class="content"><%= form.text_area :content, class: 'text-content' %></div>

    <div class="blog-image">
      <%= form.file_field :image, id: :feed_image, class:"col-md-12 col-sm-12 col-xs-12" %>
      <%= form.hidden_field :image_cache %>
    </div>


  </section>
  <ul class="edit-menu form-menu">
    <li><%= form.submit "Confirm...", id: 'btn' %></li>
  </ul>
<% end %>

app/views/blogs/edit.html.erb
<div class="back-rgba">
  <section class="login-signup">
    <h2>Post.</h2>
    <%= render "form" %>
    <ul class="edit-menu form-menu">
      <li><class="link"><%= link_to "→ Back.", blog_path(@blog.id) %></h5></li>
    </ul>
  </section>
</div>

app/views/blogs/edit_confirm.html.erb
<div class="back-rgba">
  <section class="login-signup">
    <h2>Confirm...</h2>

    <%= render "confirm" %>

    <%= form_with(model: @blog, local: true, url: edit_blog_path, method: :get) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image %>
      <div class="confirm-back-btn">
        <ul class="edit-menu col-md-2 col-sm-12">
          <li><%= form.submit "Back." , name: "back", id: 'btn' %></li>
        </ul>
      </div>
    <% end %>
  </section>
</div>

app/views/blogs/index.html.erb
<!--index-->
<h5 class="create-new"><%= link_to "→ Create new.", new_blog_path %></h5>
  <div class="row">
    <% @blogs.each do |blog| %>

    <article class="show col-md-10 col-sm-12">
      <div class="title col-md-4 col-sm-12"><%= link_to truncate(blog.title, length: 15), blog_path(blog.id) %></div>
      <div class="content col-md-6 col-sm-12">
        <%= truncate(blog.content, length: 20 )  %>
        <span><%= link_to " Continue ", blog_path(blog.id) if blog.content.length > 20 %></span>
      </div>
      <div class="author col-md-2  col-sm-12">
        <% unless blog.user_id.nil? %>
          <% if blog.user.image.present? %>
            <%= image_tag blog.user.image, class: "index-user-image" %>
          <% else %>
            <%= image_tag 'nc97179.png', class: "index-user-image" %>
          <% end %>
          <%= link_to "#{blog.user.name}", user_path(blog.user_id) unless blog.user_id.nil?  %>
        <% else %>
          <%= "　 (No author)" %>
        <% end %>
      </div>
    </article>
    <% if @current_user.id == blog.user_id %>
      <ul class="edit-menu col-md-2 col-sm-12">
        <li class="index-edit-menu">
          ( <%= link_to "→ Edit.", edit_blog_path(blog.id) %>
          <%= link_to "→ Delete.", blog_path(blog.id), method: :delete, data:{confirm: "本当に\"#{blog.title}\"を削除してもよろしいですか?"} %> )
        </li>
      </ul>
    <% end %>

    <% end %>
    <div class="page page-bottom col-md-12 col-sm-12"><%= paginate @blogs %></div>
  </div>

app/views/blogs/new.html.erb
<div class="back-rgba">
  <section class="login-signup">
    <h2>Post.</h2>
    <%= render "form" %>
    <ul class="edit-menu form-menu">
      <li><class="link"><%= link_to "→ Back.", blogs_path %></h5></li>
    </ul>
  </section>
</div>

app/views/blogs/new_confirm.html.erb
<div class="back-rgba">
  <section class="login-signup">
    <h2>Confirm...</h2>

    <%= render "confirm" %>

    <%= form_with(model: @blog, local: true, url: new_blog_path, method: :get) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image %>
      <div class="confirm-back-btn">
        <ul class="edit-menu col-md-2 col-sm-12">
          <li><%= form.submit "Back." , name: "back", id: 'btn' %></li>
        </ul>
      </div>
    <% end %>
  </section>
</div>

app/views/blogs/show.html.erb
<!--show-->
<h5 class="create-new"><%= link_to "→ Create new.", new_blog_path %></h5>
<section>
  <article class="show-content col-md-12">
    <div class="title">Title</div>
    <div class="content">
      <%= @blog.title %>
    </div>

    <% unless @blog.user_id.nil? %>
      <div class="title">Author</div>
      <div class="content">
        <%= link_to @blog.user.name, user_path(@blog.user_id) %>
      </div>
    <% end %>

    <div class="title">Content</div>
    <div class="content">
      <p><%= @blog.content %></p>

      <div class="blog-image"><%= image_tag @blog.image.url if @blog.image? %></div>

      <ul class="edit-menu show-edit-menu">
        <% if current_user.id == @blog.user_id %>
          <li>
            <%= link_to "→ Edit.", edit_blog_path(@blog.id) %>
            <%= link_to "→ Delete.", blog_path(@blog.id), method: :delete, data:{confirm: "Are you sure to delete \"#{@blog.title}\"?"} %></li>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="favorites">
      <h5>
        <% if @favorite.present? %>
          <%= link_to favorite_path(@favorite.id, blog_id: @blog.id), { method: :delete } do %>
            <span class="fa fa-heart like-btn"></span>
          <% end %>
        <% else %>
          <%= link_to favorites_path(blog_id: @blog.id), { method: :post } do %>
            <span class="fa fa-heart like-btn-unlike"></span>
          <% end %>
        <% end %>
        <% unless @blog.favorite_users.empty? %>
        <span class="favorite-users-btn"><%= pluralize(@blog.favorite_users.count, "user") %>'s favorite.</span>
        </h5>
        <ul id="favorite-users">
          <% @blog.favorite_users.each do |user| %>
            <li><%= link_to user.name, user_path(user.id) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="content">
      <ul class="edit-menu show-edit-menu">
        <li><%= link_to "→ Back.", blogs_path %></li>
      </ul>
    </div>
  </article>
</section>

<script>
  $(function(){
    $('.favorite-users-btn').click(function(){
      $('#favorite-users').slideToggle(200);
    });
  });
</script>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright by Misaki Shioi<br>
    DICオンライン2017年10月期
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if logged_in? %>
            <div class="navbar-brand" href="#"><h1><%= link_to "Simple blog.", blogs_path %></h1></div>
          <% else %>
            <div class="navbar-brand" href="#"><h1><%= link_to "Simple blog.", root_path %></h1></div>
          <% end %>
        </div>

        <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if logged_in? %>
              <li><%= link_to "→ Blogs index.", blogs_path %></li>
              <li><%= link_to "→ Create new.", new_blog_path %></li>
              <li><%= link_to "→ Profile.", user_path(current_user.id) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "→ Log out.", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "→ Log in.", new_session_path %></li>
              <li><%= link_to "→ Sign up.", new_user_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/top/index.html.erb
<section class="top">
  <h3>
    Simple blog.
    <span class="font-small">
      は世界一シンプルなブログサービスです。<br>
      １記事につき、<br>
      140文字以内の記事を気軽に投稿できます。<br>
      あなたも
    </span>
    Simple blog.
    <span class="font-small">
      でシンプルなブログ習慣をはじめてみませんか？
    </span>
  </h3>
  <h5 class="create-new"><%= link_to "→ Log in. ログインする", new_session_path %></h5>
  <h5 class="create-new"><%= link_to "→ Sign up. ユーザー登録", new_user_path %></h5>
  <!-- <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Link <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "→ Top.", root_path %></li>
      <li><%= link_to "→ Blogs index.", blogs_path %></li>
      <li><%= link_to "→ Create new.", new_blog_path %></li>
    </ul>
  </div> -->
</section>

app/views/users/_blogs.html.erb
  <h4>Blogs.</h4>
  <% unless @user_blogs.empty? %>
    <div class="page col-md-12 col-sm-12"><%= paginate @user_blogs, params:{content: :blog} %></div>
    <% @user_blogs.each do |blog| %>
      <div class="title col-md-3 col-sm-12">
        <%= link_to truncate(blog.title, length: 10 ), blog_path(blog.id) %>
      </div>
      <div class="content col-md-6 col-sm-7 col-xs-12">
        <%= truncate(blog.content, length: 30 )  %>
        <span><%= link_to " Continue ", blog_path(blog.id) if blog.content.length > 30 %></span>
      </div>
      <ul class="edit-menu col-md-3 col-sm-5 col-xs-12">
        <% if current_user.id == blog.user_id %>
          <li>
            <%= link_to "→ Edit.", edit_blog_path(blog.id) %>
            <%= link_to "→ Delete.", blog_path(blog.id), method: :delete, data:{confirm: "Are you sure to delete \"#{blog.title}\"?"} %>
          </li>
        <% else %>
          <li>
            <%= "　　" %>
         </li>
        <% end %>
      </ul>
    <% end %>
  <% else %>
    <p> No blogs yet...</p>
  <% end %>

app/views/users/_favorites.html.erb
<h4>Favorites.</h4>
<% unless @favorite_blogs.empty? %>
  <div class="page col-md-12 col-sm-12"><%= paginate @favorite_blogs, params:{content: :favorite} %></div>
  <% @favorite_blogs.each do |blog| %>
    <div class="title col-md-3 col-sm-12">
      <%= link_to truncate(blog.title, length: 10 ), blog_path(blog.id) %>
    </div>
    <div class="content col-md-6 col-sm-7 col-xs-12">
      <%= truncate(blog.content, length: 25 )  %>
      <span><%= link_to "Continue ", blog_path(blog.id) if blog.content.length > 25 %></span>
    </div>
    <div class="content fav-author col-md-3 col-sm-3 col-xs-12">
      <% if @user.id == blog.user_id %>
        <%= "　 #{@user.name}" %>
      <% else %>
        <% if blog.user.present? %>
          <%= link_to "→ #{blog.user.name}", user_path(blog.user_id) %>
        <% else %>
          <%= "　 (No author)" %>
        <% end %>
      <% end %>
    </div>
    <!-- <ul class="edit-menu col-md-3 col-sm-5 col-xs-12">
      <% if current_user.id == blog.user_id %>
        <li>
          <%= link_to "→ Edit.", edit_blog_path(blog.id) %>
          <%= link_to "→ Delete.", blog_path(blog.id), method: :delete, data:{confirm: "Are you sure to delete \"#{blog.title}\"?"} %>
        </li>
      <% end %>
    </ul> -->
  <% end %>
<% else %>
  <p> No favorites yet...</p>
<% end %>

app/views/users/_user_favorites.html.erb
<h4>Favorites.</h4>
<% unless @favorite_blogs.empty? %>
  <div class="page col-md-12 col-sm-12"><%= paginate @favorite_blogs %></div>
  <% @favorite_blogs.each do |blog| %>
    <div class="title col-md-3 col-sm-12">
      <%= link_to truncate(blog.title, length: 10 ), blog_path(blog.id) %>
    </div>
    <div class="content col-md-6 col-sm-7 col-xs-12">
      <%= truncate(blog.content, length: 25 )  %>
      <span><%= link_to "Continue ", blog_path(blog.id) if blog.content.length > 25 %></span>
    </div>
    <div class="content fav-author col-md-3 col-sm-3 col-xs-12">
      <% if @user.id == blog.user_id %>
        <%= "　 #{@user.name}" %>
      <% else %>
        <% if blog.user.present? %>
          <%= link_to "→ #{blog.user.name}", user_path(blog.user_id) %>
        <% else %>
          <%= "　 (No author)" %>
        <% end %>
      <% end %>
    </div>
    <!-- <ul class="edit-menu col-md-3 col-sm-5 col-xs-12">
      <% if current_user.id == blog.user_id %>
        <li>
          <%= link_to "→ Edit.", edit_blog_path(blog.id) %>
          <%= link_to "→ Delete.", blog_path(blog.id), method: :delete, data:{confirm: "Are you sure to delete \"#{blog.title}\"?"} %>
        </li>
      <% end %>
    </ul> -->
  <% end %>
<% else %>
  <p> No favorites yet...</p>
<% end %>

app/views/users/blogs.html.erb
<% content_for :user_contenet do %>
  <h4>Blogs.</h4>
  <% unless @user_blogs.empty? %>
    <div class="page col-md-12 col-sm-12"><%= paginate @user_blogs, params:{content: :blog} %></div>
    <% @user_blogs.each do |blog| %>
      <div class="title col-md-3 col-sm-12">
        <%= link_to truncate(blog.title, length: 10 ), blog_path(blog.id) %>
      </div>
      <div class="content col-md-6 col-sm-7 col-xs-12">
        <%= truncate(blog.content, length: 30 )  %>
        <span><%= link_to " Continue ", blog_path(blog.id) if blog.content.length > 30 %></span>
      </div>
      <ul class="edit-menu col-md-3 col-sm-5 col-xs-12">
        <% if current_user.id == blog.user_id %>
          <li>
            <%= link_to "→ Edit.", edit_blog_path(blog.id) %>
            <%= link_to "→ Delete.", blog_path(blog.id), method: :delete, data:{confirm: "Are you sure to delete \"#{blog.title}\"?"} %>
          </li>
        <% else %>
          <li>
            <%= "　　" %>
         </li>
        <% end %>
      </ul>
    <% end %>
  <% else %>
    <p> No blogs yet...</p>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="back-rgba">
  <section class="login-signup">
    <h2>Edit.</h2>
    <%= render "form" %>
  </section>
</div>

app/views/users/show.html.erb
<section>
  <div class="row user-menu">
    <h2><%= @user.name %></h2>
    <p>
      <% if @user.image.present? %>
        <%= image_tag @user.image, class: "user-image" %>
      <% else %>
        <%= image_tag 'nc97179.png', class: "user-image" %>
      <% end %>
    </p>

    <ul class="edit-menu show-edit-menu col-sm-offset-1 col-sm-11">
      <div class="change-btn">

      <% case params['content'] %>
      <% when 'blog' %>
        <div id="favorites-btn-2">→ Favorites.</div>
        <div id="blogs-btn-2">→ Blogs.</div>
      <% when 'favorite' %>
        <div id="favorites-btn-3">→ Favorites.</div>
        <div id="blogs-btn-3">→ Blogs.</div>
      <% else %>
        <div id="favorites-btn-1">→ Favorites.</div>
        <div id="blogs-btn-1">→ Blogs.</div>
      <% end %>

      </div>
      <% if current_user.id == @user.id %>
        <li><%= link_to "→ Edit your profire.", edit_user_path(@user.id) %></li>
      <% end %>
    </ul>
  </div>

  <article class="user_content row">
    <% case params['content'] %>
    <% when 'blog' %>
      <div id="blogs-show-2"><%= render "blogs" %></div>
      <div id="favorites-show-2"><%= render "favorites" %></div>
    <% when 'favorite' %>
      <div id="blogs-show-3"><%= render "blogs" %></div>
      <div id="favorites-show-3"><%= render "favorites" %></div>
    <% else %>
      <div id="blogs-show-1"><%= render "blogs" %></div>
      <div id="favorites-show-1"><%= render "favorites" %></div>
    <% end %>
  </article>
</section>

<script>
  $(function() {
    $('#favorites-btn-1').on('click', function(){
      $('#favorites-btn-1').toggle();
      $('#blogs-btn-1').toggle();
      $('#blogs-show-1').slideToggle(400);
      $('#favorites-show-1').slideToggle(400);
    });
    $('#blogs-btn-1').on('click', function(){
      $('#blogs-btn-1').toggle();
      $('#favorites-btn-1').toggle();
      $('#blogs-show-1').slideToggle(400);
      $('#favorites-show-1').slideToggle(400);
    });
  });

  $(function() {
    $('#favorites-btn-2').on('click', function(){
      $('#favorites-btn-2').toggle();
      $('#blogs-btn-2').toggle();
      $('#blogs-show-2').slideToggle(400);
      $('#favorites-show-2').slideToggle(400);
    });
    $('#blogs-btn-2').on('click', function(){
      $('#blogs-btn-2').toggle();
      $('#favorites-btn-2').toggle();
      $('#blogs-show-2').slideToggle(400);
      $('#favorites-show-2').slideToggle(400);
    });
  });

  $(function() {
    $('#favorites-btn-3').on('click', function(){
      $('#favorites-btn-3').toggle();
      $('#blogs-btn-3').toggle();
      $('#blogs-show-3').slideToggle(400);
      $('#favorites-show-3').slideToggle(400);
    });
    $('#blogs-btn-3').on('click', function(){
      $('#blogs-btn-3').toggle();
      $('#favorites-btn-3').toggle();
      $('#blogs-show-3').slideToggle(400);
      $('#favorites-show-3').slideToggle(400);
    });
  });
</script>